### ISSUE TITLE
Use Improved API to find Better Quotes.

### ISSUE THREAD

**Issue by AnjumanHasan** [Mr-Sunglasses/pastebin-telegram#17]
# Use Improved API to find Better Quotes.

## Overview
Improved API for Better Quotes.

## Description
Current the [quotes.py](https://github.com/Mr-Sunglasses/pastebin-telegram/blob/master/pastebin-bot/quotes.py) is using a very old api to find quotes, the goal is to find a new and better Api to find Quotes.
## Expected outcomes

New Api for better Quotes.
## Skills

Python, Request.

## Possible mentors
[Kanishk Pachauri](https://github.com/Mr-Sunglasses), [Anjuman Hassan](https://github.com/AnjumanHasan)

## Expected project size

1 hours.

## Difficulty

Easy

**Comment by aesyklos07** [comment]
I'm interested on working on this project. I'm new to open source, kindly guide me how to proceed further.

**Comment by devAyushDubey** [comment]
I want to work on this.

**Comment by Mr-Sunglasses** [comment]
thanks, @devAyushDubey for contributing, it is working like a charm 🎉, you can checkout your work by using [pastebin-telegram bot](https://t.me/Source_101_bot) and use command `/quote`

**Comment by devAyushDubey** [comment]
> thanks, @devAyushDubey for contributing, it is working like a charm 🎉, you can checkout your work by using [pastebin-telegram bot](https://t.me/Source_101_bot) and use command `/quote`

Thanks @Mr-Sunglasses , I would love to contribute to more of your open source projects😀.
